LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := RemovePackages
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_OVERRIDES_PACKAGES += GoogleTV
LOCAL_OVERRIDES_PACKAGES += OemDmTrigger
LOCAL_OVERRIDES_PACKAGES += GoogleTVPrebuilt
LOCAL_OVERRIDES_PACKAGES += Chrome
LOCAL_OVERRIDES_PACKAGES += ChromeStub
LOCAL_OVERRIDES_PACKAGES += com.android.chrome
LOCAL_OVERRIDES_PACKAGES += com.android.camera2
LOCAL_OVERRIDES_PACKAGES += Camera
LOCAL_OVERRIDES_PACKAGES += Camera2
LOCAL_OVERRIDES_PACKAGES += YTMusic
LOCAL_OVERRIDES_PACKAGES += YoutubeMusic
LOCAL_OVERRIDES_PACKAGES += com.google.android.apps.youtube.music
LOCAL_OVERRIDES_PACKAGES += YouTubeMusicPrebuilt
LOCAL_OVERRIDES_PACKAGES += YouTube
LOCAL_UNINSTALLABLE_MODULE := true
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := /dev/null
include $(BUILD_PREBUILT)
